version: "3"

services:
  with-docker-multi-env-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: with-docker-multi-env-production
    ports:
      - "0.0.0.0:3333:3333"
